// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportStore.Models;

namespace SportStore.Migrations.HaberDb
{
    [DbContext(typeof(HaberDbContext))]
    [Migration("20230109230630_degisiklik")]
    partial class degisiklik
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportStore.Models.Haber", b =>
                {
                    b.Property<long>("HaberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HaberBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberIcerigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HaberTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("HaberId");

                    b.ToTable("Haberler");
                });
#pragma warning restore 612, 618
        }
    }
}
